#####################################
# Application
#####################################

app.name=RetailLakehouse


#####################################
# Environment
#####################################

environment=dev


#####################################
# Spark
#####################################

spark.master=local[*]

spark.sql.shuffle.partitions=4

spark.sql.warehouse.dir=./data/dev/warehouse


#####################################
# Hive
#####################################

hive.metastore.path=./data/dev/metastore_db


#####################################
# Storage
#####################################

data.root=./data/dev

bronze.path=./data/dev/bronze

silver.path=./data/dev/silver

gold.path=./data/dev/gold


#####################################
# Dataset Source
#####################################

dataset.root=../data/olist_ecom_dataset

customers.csv=olist_customers_dataset.csv

orders.csv=olist_orders_dataset.csv

products.csv=olist_products_dataset.csv

payments.csv=olist_order_payments_dataset.csv

order_items.csv=olist_order_items_dataset.csv