#####################################
# Application
#####################################

app.name=RetailLakehouse


#####################################
# Environment
#####################################

environment=dev


#####################################
# Spark
#####################################

spark.master=local[*]

spark.sql.shuffle.partitions=4

spark.sql.warehouse.dir=./data/dev/warehouse


#####################################
# Storage
#####################################

data.root=./data/dev

raw.path=./data/dev/raw

curated.path=./data/dev/curated

reports.path=./data/dev/reports


#####################################
# Dataset Source
#####################################

dataset.root=/home/anand/projects/bigdata/data/olist_ecom_dataset

customers.csv=olist_customers_dataset.csv

orders.csv=olist_orders_dataset.csv

products.csv=olist_products_dataset.csv

payments.csv=olist_order_payments_dataset.csv