#####################################
# Application
#####################################

app.name=RetailLakehouse


#####################################
# Environment
#####################################

environment=dev


#####################################
# Spark
#####################################

spark.master=local[*]

spark.sql.shuffle.partitions=4

spark.sql.warehouse.dir=./data/dev/warehouse

#####################################
# Storage
#####################################

data.root=./data/dev

raw.path=./data/dev/raw

curated.path=./data/dev/curated

reports.path=./data/dev/reports